### ISSUE TITLE
Getting Traceback errors before running backup

### ISSUE THREAD

**Issue by xentek** [jspringman/cloudcity#1]
Cloudcity is all set up, and has worked flawlessly in the past. In fact, restores still work fine, but when I run it lately I get this:

https://gist.github.com/735195

Then it basically hangs here and doesn't ever really complete. So the backups aren't reliable and aren't necessarily being updated properly either when this runs, since it never completes.

I'm using the correct versions of duplicity 0.5.18 and the latest version of python-cloudfiles from github.

What can I do to get this working again?

**Comment by jspringman** [comment]
Did you resolve this problem, xentek? I don't know why it's happening, but, considering the 404 error, I wonder if there's something funky with the Cloud Files container in question. I've not encountered this, myself. Perhaps you could create a new container for testing. Let me know what you find. My apologies for taking forever to respond.

**Comment by xentek** [comment]
That server is no longer up, but I'm about to give cloudcity another spin on my latest cluster and will let you know if I run into any issues. Thanks for responding!

**Comment by xentek** [comment]
Also, for what its worth, I think my problems were also related to the fact that the server in question was also pretty full and didn't have a lot of disk space for cloudcity to do its thing, so that was probably the issue. My memory is a little fuzzy on this, but I'd consider this issue closed.
