### ISSUE TITLE
Quotes missing - "unary operator expected"

### ISSUE THREAD

**Issue by guiambros** [jspringman/cloudcity#2]
Restoring files with ./cloudcity.sh -a 1 returns 

```
./cloudcity.sh: line 166: [: ==: unary operator expected
```

It's just a matter of using double quotes around the first arg on line 166:

```
 if [ "${file:0:1}" == "/" ]; then
```

**Comment by jspringman** [comment]
Thanks for your help on this, guiambros. I updated the script.
