### ISSUE TITLE
You may only restore one file or directory at a time

### ISSUE THREAD

**Issue by ashworthconsulting** [jspringman/cloudcity#3]
We're running into an issue while testing restoration. We've backed up successfully for several days, and are getting this error while attempting to restore:

```
 # ./cloudcity a1 /home/usernamehere/
 You may only restore one file or directory at a time.
```

Attempted so far with no luck:

```
 # ./cloudcity a1 /home/usernamehere/
 # ./cloudcity a1 /home/usernamehere
 # ./cloudcity a1 /home/usernamehere/*
```

I've tried the following to list out files, and verified that the path definitely exists:

```
 # ./cloudcity -l
```

We've checked, and the restoration path does exist on the server, with write permissions given to the user running the `cloudcity` script.

If it helps, we're using Rackspace Cloud Files to store the data, but so far nothing has given me reason to think there's anything wrong with the connection between the server and Rackspace.

**Comment by jspringman** [comment]
Options ("a1" in your case) must be preceded by a dash. This will work:

```
./cloudcity -a1 /home/usernamehere
```

**Comment by ashworthconsulting** [comment]
Ugh. I feel like an idiot...I knew better.

Thanks for chiming in so soon. Much appreciated!
