### ISSUE TITLE
PASSPHRASE variable question

### ISSUE THREAD

**Issue by ashworthconsulting** [jspringman/cloudcity#4]
I'm considering adapting this with your permission to utilize some other protocols for transfer (scp for example). I've decided to use a separate dedicated system for backup housing as Rackspace and S3 might not be right for what we're doing.

However, I'm noticing in the bash script that the variable "PASSPHRASE" doesn't seem to be called anywhere below where it's set in the export command. If it's not being accessed below in the script, how exactly are our backups using the key?

None of the duplicity commands seem to be using this variable. Thanks!

**Comment by ashworthconsulting** [comment]
Unless duplicity just automatically looks for PASSPHRASE in the environment. Maybe I'm just confused.

**Comment by jspringman** [comment]
Feel free to adapt the script in any way you see fit. As for the PASSPHRASE environmental variable, if it's not set, you'll be prompted for the passphrase, thus preventing automation of backups.
